### ISSUE TITLE
Error: Invalid binary plist. Expected 'bplist' at offset 0.

### ISSUE THREAD

**Issue by scott-m-sarsfield** [sindresorhus/default-browser-id#4]
Might be my machine, but when running the usage script. I get the error:

```
➜  browser-id-test npx ts-node test.js
/Users/scott.sarsfield/browser-id-test/node_modules/bplist-parser/bplistParser.js:55
    throw new Error("Invalid binary plist. Expected 'bplist' at offset 0.");
          ^
Error: Invalid binary plist. Expected 'bplist' at offset 0.
    at Object.exports.parseBuffer (/Users/scott.sarsfield/browser-id-test/node_modules/bplist-parser/bplistParser.js:55:11)
    at defaultBrowserId (file:///Users/scott.sarsfield/browser-id-test/node_modules/default-browser-id/index.js:27:22)
    at async file:///Users/scott.sarsfield/browser-id-test/test.js:2:13
➜  browser-id-test npm ls
browser-id-test@1.0.0 /Users/scott.sarsfield/browser-id-test
└── default-browser-id@3.0.0
```

Running on a 2019 MacBook Pro w/ 2.6 GHz intel

**Comment by scott-m-sarsfield** [comment]
So, it worked itself out after running:
```
cd ~/Library/Preferences/ 
rm com.apple.Safari.*
rm com.apple.internet*.plist
```
and manually setting the default browser again.  (my machine was resetting the default browser on restart, so it was an issue with my machine). 

Thanks.

**Comment by pioneer32** [comment]
FYI 
I've just come across the same error.

The reason was:
`~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist` wasn't binary, but instead plaintext. Some software modified it and left this plaintext.

A work-around here for me was: I changed the default browser (via the OS Settings) to Safari and then back to Chrome - this resulted in updating `~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist` by MacOS and that fixed the problem
